server:
  port: 1022
---
spring:
  datasource:
    username: survey
    password: 1234
    url: jdbc:mariadb://localhost:3306/survey
    driver-class-name: org.mariadb.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    open-in-view: false

util:
  encrypt:
    secretKey: trqkfow29fj20fchg95761kjfsd345we
  jwt:
    secretKey: vxjf91kfoqiwuejcuzghqpmvzzd36nht
    refreshKey: vxjf91kfoqiwuejcuzghqpmvzzd36nht
    defaultExpirationMinutes: 60

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.seung.survey